version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:      
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - ls /root/.m2/      
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - echo Docker Build      
      - docker build -t $REPOSITORY_URI:latest -f DockerfileForADOT .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo ECR Docker Push      
      - docker push $REPOSITORY_URI:latest      
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - ls /root/.m2/
#artifacts:
#  files:
    #- target/sample-schedulelaunch*.jar

cache:
  paths:
    - '/root/.m2/**/*'