logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    
#delayed:
#  batch:
#    queues:
#      sample-batch:
#        name: SampleQueue
    
#aws:
#  sqs:
#    sqslocal:    
#      port: 18001