spring:
  # Spring Cloud for AWS Parameter Store Integration Enabled
  cloud:
    aws:
      parameterstore:
        enabled: true
  config:
    import: 
      - optional:aws-parameterstore:/config/common/;/config/${spring.application.name}/
   
# 拡張フレームワーク機能の設定    
#example:
#  sqs:
#    sqslocal:
#      port: 18001
# 業務APの設定
#  delayed:
#    batch:
#      queues:
#        sample-batch:
#          name: SampleQueue
