spring:
  # Spring Cloud for AWS Parameter Store Integration Enabled
  cloud:
    aws:
      parameterstore:
        enabled: true
  config:
    import: 
      - optional:aws-parameterstore:/config/common/;/config/${spring.application.name}/
   
#delayed:
#  batch:
#    queues:
#      sample-batch:
#        name: SampleQueue
    
#aws:
#  sqs:
#    sqslocal:    
#      port: 18001