# Spring Cloud for AWS Parameter Store & Integration Secreters Manager Integration
spring:
  config:
    import: 
      - aws-parameterstore:/config/common;/config/sample-schedulelaunch

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    
#delayed:
#  batch:
#    queues:
#      sample-batch:
#        name: SampleQueue
    
#aws:
#  sqs:
#    sqslocal:    
#      port: 18001