logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

# 拡張フレームワーク機能の設定    
example:
  sqs:
    sqslocal:
      port: 18001
# 業務APの設定
  delayed:
    batch:
      queues:
        sample-batch:
          name: SampleQueue
